### ISSUE TITLE
Remove empty collections from schema

### ISSUE THREAD

**Issue by bartkl** [bartkl/cim-to-linkml#3]
Top-level packages that contain no classes and enums have empty keys for each:

```yaml
enums:
classes:
subsets: {}
```

I'd rather have these removed.
