### ISSUE TITLE
Redundancy: name slot for all elements

### ISSUE THREAD

**Issue by bartkl** [bartkl/cim-to-linkml#7]
```yaml
  PerLengthImpedance:
    name: PerLengthImpedance
    attributes:
      ACLineSegments:
        name: ACLineSegments
        range: ACLineSegment
```

Better might be:

```yaml
  PerLengthImpedance:
    attributes:
      ACLineSegments:
        range: ACLineSegment
```
